CREATE TABLE transactions (
    TRANSACTION_ID INT PRIMARY KEY,
    TX_DATETIME TIMESTAMPTZ,
    CUSTOMER_ID INT,
    TERMINAL_ID INT,
    TX_AMOUNT FLOAT,
    MERCHANT_ID INT,
    IS_ONLINE BOOLEAN,
    TX_FRAUD BOOLEAN,
    TX_FRAUD_SCENARIO VARCHAR(255),
    CUSTOMER_IS_COMPROMISED BOOLEAN,
    MERCHANT_IS_COMPROMISED BOOLEAN,
    TERMINAL_IS_COMPROMISED BOOLEAN,
    TERMINAL_X FLOAT,
    TERMINAL_Y FLOAT
);

CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE embeddings (
    id SERIAL PRIMARY KEY,
    embedding VECTOR(64),
    name TEXT,
    transaction_references INT[]
);
