version: '3'
services:
  nats:
    image: nats
    ports:
      - "4222:4222"
      - "8222:8222"

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: transactions
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z

  dbhandler:
    build: ./dbhandler
    depends_on:
      - nats
      - postgres

volumes:
  postgres_data:
